name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  setup-soft-roce:
    name: Setup Soft-RoCE
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - id: setup
        uses: ./
      - name: Verify Soft-RoCE
        env:
          DEVICE_NAME: ${{ steps.setup.outputs.device-name }}
        run: rdma link show "$DEVICE_NAME/1"
